/*
* Configuration of module: CanTp (CanTp_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.0
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Fri Sep 23 15:10:53 CEST 2011
*/


#ifndef CANTP_CFG_H_
#define CANTP_CFG_H_

//#define CANTP_MAIN_FUNCTION_PERIOD_TIME_MS	20
//#define CANTP_CONVERT_MS_TO_MAIN_CYCLES(x)  ((x)/CANTP_MAIN_FUNCTION_PERIOD_TIME_MS)

//#define CANTP_NSDU_CONFIG_LIST_SIZE		2
//#define CANTP_NSDU_RUNTIME_LIST_SIZE	2

//#define FRTP_CANCEL_TRANSMIT_REQUEST 	STD_ON
#define CANTP_VERSION_INFO_API          STD_ON   /**< Build version info API */
#define CANTP_DEV_ERROR_DETECT          STD_OFF
  
//#define CANTP_PDU_ID_PDU_UDSphysicalRX		0
//#define CANTP_PDU_ID_PDU_UDSphysicalTX		0 
//#define CANTP_PDU_ID_PDU_functionalRX		1
//#define CANTP_PDU_ID_PDU_functionalTX		1

extern const CanTp_ConfigType CanTpConfig;
//extern const CanTp_NSduType CanTpNSduConfigList[];

typedef struct {
} CanTp_RxNPduType; // id för inkommande N-PDUer från CanIf
typedef struct {
} CanTp_TxNPduType; // id för utskickade N-PDUer till CanIf
typedef struct {
} CanTp_RxNSduType; // id för inkommande N-SDUer till PduR
typedef struct {
} CanTp_TxNSduType; // id för utskickade N-SDUer från PduR

#endif /* CANTP_CFG_H_ */
