/*
* Configuration of module: CanTp (CanTp_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.0
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Fri Sep 23 15:10:53 CEST 2011
*/


#include "CanTp.h"
#if defined(USE_CANIF)
#include "CanIf.h"
#endif
#if defined(USE_PDUR)
#include "PduR.h"
#endif

const CanTp_GeneralType CanTpGeneralConfig =
{
  .main_function_period = 20,
};


//NSa
const CanTp_NSaType CanTpNSaConfig_RxNSdu_physical = 
{	
	.CanTpNSa = 0,
};
const CanTp_NSaType CanTpNSaConfig_RxNSdu_functional = 
{	
	.CanTpNSa = 0,
};		

//NTa
const CanTp_NTaType CanTpNTaConfig_RxNSdu_physical = 
{
  .CanTpNTa = 0,
};
const CanTp_NTaType CanTpNTaConfig_RxNSdu_functional = 
{
  .CanTpNTa = 0,
};

const CanTp_NSduType CanTpNSduConfigList[] =
{
	{
		.direction = ISO15765_RECEIVE,				
		.configData.CanTpRxNSdu.CanIf_FcPduId = CANIF_PDU_ID_PDU_UDSphysicalTX,
		.configData.CanTpRxNSdu.PduR_PduId = PDUR_DEST_PDU_ID_PDU_UDSphysicalRX,
		.configData.CanTpRxNSdu.CanTpRxChannel = 0,	
		.configData.CanTpRxNSdu.CanTpAddressingFormant = CANTP_STANDARD,
		.configData.CanTpRxNSdu.CanTpBs = 0,
		.configData.CanTpRxNSdu.CanTpNar = 0,
		.configData.CanTpRxNSdu.CanTpNbr = 0,
		.configData.CanTpRxNSdu.CanTpNcr = 0,
		.configData.CanTpRxNSdu.CanTpRxDI = 0,
		.configData.CanTpRxNSdu.CanTpRxPaddingActivation = CANTP_OFF,
		.configData.CanTpRxNSdu.CanTpRxTaType = CANTP_PHYSICAL,
		.configData.CanTpRxNSdu.CanTpWftMax = 0,
		.configData.CanTpRxNSdu.CanTpSTmin = 0,
		.configData.CanTpRxNSdu.CanTpNSa = &CanTpNSaConfig_RxNSdu_physical,
		.configData.CanTpRxNSdu.CanTpNTa = &CanTpNTaConfig_RxNSdu_physical,
		.listItemType = CANTP_NOT_LAST_ENTRY,	
	},
	{
		.direction = ISO15765_RECEIVE,				
		.configData.CanTpRxNSdu.CanIf_FcPduId = CANIF_PDU_ID_PDU_functionalTX,
		.configData.CanTpRxNSdu.PduR_PduId = PDUR_DEST_PDU_ID_PDU_functionalRX,
		.configData.CanTpRxNSdu.CanTpRxChannel = 1,	
		.configData.CanTpRxNSdu.CanTpAddressingFormant = CANTP_STANDARD,
		.configData.CanTpRxNSdu.CanTpBs = 0,
		.configData.CanTpRxNSdu.CanTpNar = 0,
		.configData.CanTpRxNSdu.CanTpNbr = 0,
		.configData.CanTpRxNSdu.CanTpNcr = 0,
		.configData.CanTpRxNSdu.CanTpRxDI = 0,
		.configData.CanTpRxNSdu.CanTpRxPaddingActivation = CANTP_OFF,
		.configData.CanTpRxNSdu.CanTpRxTaType = CANTP_FUNCTIONAL,
		.configData.CanTpRxNSdu.CanTpWftMax = 0,
		.configData.CanTpRxNSdu.CanTpSTmin = 0,
		.configData.CanTpRxNSdu.CanTpNSa = &CanTpNSaConfig_RxNSdu_functional,
		.configData.CanTpRxNSdu.CanTpNTa = &CanTpNTaConfig_RxNSdu_functional,
		.listItemType = CANTP_NOT_LAST_ENTRY,	
	},
};

const CanTp_ConfigType CanTpConfig =
{
  .CanTpNSduList 	= 	CanTpNSduConfigList,
  .CanTpGeneral 	= 	&CanTpGeneralConfig,
};
